server:
  port: 8080
  servlet:
    context-path: /legal-case-management

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  application:
    name: neu
  datasource:
    url: "jdbc:mysql://localhost:3306/legal_case_management"
    username: root
    password: 123456
  mail:
    host: smtp.gmail.com
    port: 587
    username: quangdang111104@gmail.com
    password: glqf cwra hxed lyqu
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true


logging:
  level:
    org:
      springframework:
        security: DEBUG
